version: 2.1
jobs:
  deploy_prod: # ジョブ名
    docker:
      - image: circleci/node:10.16.3 # ジョブ実行環境のDockerイメージを記述
    steps:
      - checkout # ソースコードのチェックアウト
      - run: # 順に実行したいコマンドとコマンドに名前をつけます
          name: install
          command: yarn install
      - run:
          name: build
          command: yarn build
          env:
            CI: false
      - run:
          name: deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN # プロジェクト上のfirebase-toolsでデプロイします

workflows:
  version: 2
  deploy_prod: # ワークフローの名前
    jobs:
      - deploy_prod: # 上で定義したジョブを指定します
          filters:
            branches:
              only: master # masterブランチのみを実行対象とします
